implemented task 'Spring Boot Web'
alex-hazniuk/online-book-store pull request #2
Opened 2023-09-13 12:06 UTC by alex-hazniuk

2023-09-13 17:08 UTC, aaananas requested changes

2023-09-13 17:08 UTC, aaananas commented on src/main/java/com/example/onlinebookstore/repository/BookRepositoryImpl.java
> +        }
it should be try-catch-finally, not try with resources

2023-09-14 09:55 UTC, Rommelua approved these changes

2023-09-14 09:55 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +
you can use lombok -
@Getter
@Setter
@NoArgsConstructor

2023-09-14 11:16 UTC, merged